language: python

env:
  REGISTRY_IMAGE: eurodatacube/ogc-edc

services:
  - docker

install:
  - docker pull "$REGISTRY_IMAGE:latest" || true
  - docker build --cache-from "$REGISTRY_IMAGE:latest" -t "$REGISTRY_IMAGE:tmp_build" .

script:
  - true

deploy:
  provider: script
  script: bash -x travis_deploy.sh
